### ISSUE TITLE
24K纯小白运行失败

### ISSUE THREAD

**Issue by xieyabos** [moonlightL/ml-blog#1]
建议大牛搞一个交流群   ，冷汗 尴尬

请教一个十分基础的错误，我将您的代码下载下来，用idea打开，但是却无法运行，
我也清除缓存重启了，依旧是看这样，请问应该是哪里出问题了您

运行程序提示：“错误: 找不到或无法加载主类 com.extlight.MlBlogApplication”
main函数的 ‘SpringApplication’为红色 提示 Cannot resolve symbol 'SpringApplication'
main函数上面的Override有红色下划线，提示 Method does not override method from its superclass

**Comment by moonlightL** [comment]
445847261 加qq 私聊吧

**Comment by moonlightL** [comment]
> 建议大牛搞一个交流群 ，冷汗 尴尬
> 
> 请教一个十分基础的错误，我将您的代码下载下来，用idea打开，但是却无法运行，
> 我也清除缓存重启了，依旧是看这样，请问应该是哪里出问题了您
> 
> 运行程序提示：“错误: 找不到或无法加载主类 com.extlight.MlBlogApplication”
> main函数的 ‘SpringApplication’为红色 提示 Cannot resolve symbol 'SpringApplication'
> main函数上面的Override有红色下划线，提示 Method does not override method from its superclass

**Comment by moonlightL** [comment]
> 建议大牛搞一个交流群 ，冷汗 尴尬
> 
> 请教一个十分基础的错误，我将您的代码下载下来，用idea打开，但是却无法运行，
> 我也清除缓存重启了，依旧是看这样，请问应该是哪里出问题了您
> 
> 运行程序提示：“错误: 找不到或无法加载主类 com.extlight.MlBlogApplication”
> main函数的 ‘SpringApplication’为红色 提示 Cannot resolve symbol 'SpringApplication'
> main函数上面的Override有红色下划线，提示 Method does not override method from its superclass

445847261 加群私聊吧
